#+title: update-dtbook-metadata

A tiny xml transformer that will update the meta data in your DTBook
file and only that. No entity expansion, no anything! You get your
original xml back with the updated meta data.

* Installation
Clone and build with

#+begin_example
mvn clean package
#+end_example

** Versioning
The maven build uses the [[https://github.com/qoomon/maven-git-versioning-extension][maven-git-versioning-extension]] which will
label the build artifacts accordingly. In order for this to work you
will have to tag the source and checkout this tag before building (see
https://github.com/qoomon/maven-git-versioning-extension#configure-extension).

* Usage

#+begin_example
java -DDC.TITLE="New Title" -jar update-dtbook-metadata-1.0-jar-with-dependencies.jar < original.xml > updated.xml
#+end_example

** Valid meta data properties
The following meta data names are recognized. The corresponding Java
System property can be derived by replacing the ~:~ with ~.~ and
uppercasing the resulting string. So ~dc:Publisher~ can be set by
using the ~DC.PUBLISHER~ system property.

- dc:Title
- dc:Creator
- dc:Subject
- dc:Description
- dc:Publisher
- dc:Date
- dc:Type
- dc:Format
- dc:Identifier
- dc:Source
- dc:Language
- dc:Rights
- dtb:uid
- dtb:sourceEdition
- dtb:sourcePublisher
- dtb:sourceRights
- prod:series
- prod:seriesNumber
- prod:source

* Contributing
If you have any improvements or comments please feel free to file a
pull request or an issue.

* Credits
Based on ideas on [[https://stackoverflow.com/a/36097922][how to make a StaX transformer]], a [[https://www.vogella.com/tutorials/JavaXML/article.html][Java and XML
tutorial]] and most importantly on [[https://stackoverflow.com/q/1777878][how to disable entity expansion]].

* License
Copyright © 2019 [[https://www.sbs.ch/][Swiss Library for the Blind, Visually Impaired and
Print Disabled]].

Distributed under the [[http://www.gnu.org/licenses/gpl-3.0.html][GNU General Public License]]. See the file
LICENSE.

